.TH STRAT 1
.SH NAME
strat \- execute a command in a particular stratum
.SH SYNOPSIS
.B strat
[\fB\-\-arg0\fR \fINAME\fR]
[\fB\-l\fR | \fB\-\-local\fR]
.IR stratum
.IR command ...
.SH DESCRIPTION
This document describes the \fBstrat\fR command, used to execute a command in a specific stratum. The \fBstrat\fR command is part of the Bedrock Linux userland ⟨https://bedrocklinux.org⟩.
.P
.B strat
provides the ability to run commands in strata, properly handling
local-context switches.
.SS CONFIGURATION
If there exists a root-owned, only-root-writable file at

.PP
.nf
.RS
/bedrock/run/enabled_strata/<stratum-name>
.RE
.fi
.PP

.B strat
will allow users to run software from that stratum, switching out local
context files accordingly.  If this file does not exist or is writable by
anyone other than root, \fBstrat\fR will refuse to operate.  Be sure the stratum's files
exist at \fI/bedrock/strata/<stratum-name>\fR and that \fIbrl(1)\fR has set it up
(check \fBbrl status <stratum-name>\fR).  This should "just work" on a properly setup
Bedrock Linux system.

.SH OPTIONS
.TP
The command line is NOT parsed according to the usual GNU convention. The whitespace between a command line option and its argument is NOT optional. Options MAY NOT be grouped behind a single \(aq\-\(aq (minus character).
.TP
.BR \-\-arg0 " " \fINAME
.R Passes \fINAME\fR as the first (zeroth) argument to \fIcommand\fR. This is needed to support cross\-stratum login shells, as \fBlogin(1)\fR communicates to the given shell that it is a login shell through \fIargv[0]\fR. Some other programs make use of \fIargv[0]\fR, such as \fBbusybox(1)\fR
.TP
.BR \-l ", " \-\-local
.R Restricts all commands to running only in the specified stratum. For example, when building something, it may be useful to ensure the build is not dependent across strata. This argument disables cross\-stratum functionality for the command.
.SH EXIT STATUS
.B strat
.R returns the exit status of the command if it was able to execute. If it could not find the command in the specified stratum, or the command was not executable, it exits with the status 1.
.SH FILES
.IR /bedrock/etc/strata.conf " \- holds configuration for the strata that"
.B strat
.R can execute commands in
.P
.I /bedrock/run/enabled_strata/
.R Holds root-owned non-world-writeable files that \fBstrat\fR uses to determine if commands are runnable in the given strata
.SH NOTES
.B strat
was known as
.B brc
until Bedrock Linux 0.7.0 Poki
.SH BUGS
Please report any bugs you find by opening an issue at \fIhttps://github.com/bedrocklinux/bedrocklinux\-userland\fR or talking to \fIparadigm\fR in \fI#bedrock\fR on \fIirc.freenode.com\fR.
.SH EXAMPLE
To run a command in a specific stratum, just pass the stratum followed by the command and its arguments. For example:
.PP
.nf
.RS
$ \fBstrat arch lsb_release \-i\fR
Distributor ID: Arch
$ \fBstrat artful lsb_release \-i\fR
Distributor ID: Ubuntu
.RE
.fi
.PP
Using the \fB\-l\fR or \fB\-\-local\fR flag will prevent the running command from executing subcommands in a different stratum. For example, if you had gcc installed in another stratum, but not installed in arch, you could prevent arch from using it like this:
.PP
.nf
.RS
.R $ \fBstrat arch make\fR
gcc     test.c   \-o test
.R $ \fBrm test\fR
.R $ \fBstrat \-\-local arch make\fR
gcc     test.c   \-o test
make: gcc: Command not found
make: *** [Makefile:2: test] Error 127
.RE
.fi
.PP
.SH SEE ALSO
.B brl(1)
